{
    'name': 'Hospital Management System',
    'version': '1.0',
    'category': 'Healthcare',
    'summary': 'Manage patients, doctors, and departments',
    'description': 'A complete hospital management system',
    'depends': ['base', 'crm'],
    'data': [
        'security/hms_security.xml',
        'security/hms_record_rules.xml',
        'security/ir.model.access.csv',
        'views/patient_views.xml',
        'views/department_views.xml',
        'views/doctor_views.xml',
        'views/customers_views.xml',
        'report/patient_report.xml',
        'report/patient_report_template.xml',
    ],
    'installable': True,
    'application': True,
}
